export type RecipeNutrition = {
  calories: string;
  protein: string;
  carbs: string;
  fat: string;
};

export type Recipe = {
  slug: string;
  title: string;
  summary: string;
  prepTime: string;
  cookTime: string;
  servings: string;
  ingredients: string[];
  instructions: string[];
  tip: string;
  nutrition: RecipeNutrition;
  featuredProductId?: string;
  image?: string;
  bariatricApproved?: boolean;
};

export const RECIPES: Recipe[] = [
  {
    slug: "protein-pancakes",
    title: "Protein Pancakes",
    summary:
      "Fluffy pancakes with a full scoop of protein powder baked in, so breakfast stops being the weakest meal of your day for hitting your target.",
    prepTime: "5 min",
    cookTime: "10 min",
    servings: "2 (about 6 pancakes)",
    ingredients: [
      "1 scoop (about 30g) vanilla or unflavored whey or plant protein powder",
      "1 cup old-fashioned oats, blended into flour",
      "1 ripe banana, mashed",
      "2 eggs (or 1/2 cup egg whites)",
      "1/2 cup milk of choice",
      "1 tsp baking powder",
      "1/2 tsp cinnamon",
    ],
    instructions: [
      "Blend the oats in a blender or food processor until they reach a fine, flour-like texture.",
      "In a bowl, whisk the mashed banana, eggs, and milk together until smooth.",
      "Add the oat flour, protein powder, baking powder, and cinnamon. Stir until just combined — a few lumps are fine.",
      "Heat a lightly oiled non-stick pan or griddle over medium-low heat.",
      "Pour 1/4 cup of batter per pancake and cook 2-3 minutes per side, until bubbles form and the edges look set.",
      "Flip and cook another 1-2 minutes until golden. Serve with fruit or a light drizzle of syrup.",
    ],
    tip: "Protein powder can make batter dry out fast in the pan — keep the heat medium-low so the pancakes cook through before the outside burns.",
    nutrition: {
      calories: "~310 kcal",
      protein: "~28g",
      carbs: "~32g",
      fat: "~8g",
    },
    featuredProductId: "17",
    image: "/recipes/protein-pancakes.png",
  },
  {
    slug: "protein-overnight-oats",
    title: "Protein Overnight Oats",
    summary:
      "Zero-cook, make-ahead breakfast that mixes a scoop of protein powder straight into the oats so you're not choking down a chalky shake before work.",
    prepTime: "5 min (plus overnight in the fridge)",
    cookTime: "None",
    servings: "1",
    ingredients: [
      "1/2 cup old-fashioned oats",
      "1 scoop (about 30g) protein powder, any flavor",
      "3/4 cup milk of choice",
      "1/4 cup Greek yogurt",
      "1 tsp chia seeds (optional)",
      "1/2 tsp vanilla extract",
      "Toppings: berries, sliced banana, or peanut butter",
    ],
    instructions: [
      "Add the oats, protein powder, milk, Greek yogurt, chia seeds, and vanilla to a jar or container.",
      "Stir well, making sure there are no dry pockets of protein powder at the bottom.",
      "Cover and refrigerate for at least 4 hours, ideally overnight.",
      "Stir again before eating — add a splash more milk if it's thicker than you like.",
      "Top with fruit or nut butter right before serving.",
    ],
    tip: "Stir hard and stir twice — once right after mixing and once the next morning. Protein powder settles and clumps at the bottom of the jar if you skip the second stir.",
    nutrition: {
      calories: "~360 kcal",
      protein: "~35g",
      carbs: "~38g",
      fat: "~9g",
    },
    featuredProductId: "130",
    image: "/recipes/protein-overnight-oats.png",
  },
  {
    slug: "protein-mug-cake",
    title: "Protein Mug Cake",
    summary:
      "A single-serving cake that's done in under two minutes in the microwave — the fastest way to make a protein powder tub feel like dessert.",
    prepTime: "2 min",
    cookTime: "1-2 min (microwave)",
    servings: "1",
    ingredients: [
      "1 scoop (about 30g) chocolate or vanilla protein powder",
      "2 tbsp almond flour or oat flour",
      "1/2 tsp baking powder",
      "1 egg (or 3 tbsp egg whites)",
      "3 tbsp milk of choice",
      "1 tsp cocoa powder (optional, for chocolate version)",
      "A few chocolate chips (optional)",
    ],
    instructions: [
      "In a large microwave-safe mug, whisk together the protein powder, flour, baking powder, and cocoa powder if using.",
      "Add the egg and milk, and stir until the batter is smooth with no dry clumps.",
      "Fold in chocolate chips if using.",
      "Microwave on high for 60-90 seconds, checking at 60 — it's done when the center springs back and isn't wet.",
      "Let it cool for a minute before eating straight out of the mug.",
    ],
    tip: "Don't overcook it. Protein powder firms up fast in the microwave, and an extra 30 seconds is the difference between a soft cake and a rubbery one.",
    nutrition: {
      calories: "~280 kcal",
      protein: "~30g",
      carbs: "~16g",
      fat: "~10g",
    },
    featuredProductId: "1",
    image: "/recipes/protein-mug-cake.png",
  },
  {
    slug: "protein-smoothie",
    title: "Protein Smoothie",
    summary:
      "The baseline recipe everything else gets compared to — a thick, balanced smoothie built around a single scoop of protein powder.",
    prepTime: "5 min",
    cookTime: "None",
    servings: "1",
    ingredients: [
      "1 scoop (about 30g) protein powder, any flavor",
      "1 cup milk of choice or water",
      "1 frozen banana (or 1/2 cup frozen berries)",
      "1 tbsp peanut butter or almond butter (optional)",
      "1/2 cup ice",
      "Handful of spinach (optional, doesn't change the taste)",
    ],
    instructions: [
      "Add the liquid to the blender first — this keeps the protein powder from clumping against the blades.",
      "Add the protein powder, frozen fruit, nut butter, and spinach if using.",
      "Blend on high for 30-45 seconds until completely smooth.",
      "Add ice and blend again for a thicker, colder texture. Add a splash more liquid if it's too thick to blend.",
    ],
    tip: "Liquid first, powder second is the single biggest fix for gritty or clumpy smoothies — protein powder mixes far better once it's already surrounded by liquid instead of sitting at the bottom.",
    nutrition: {
      calories: "~320 kcal",
      protein: "~32g",
      carbs: "~30g",
      fat: "~8g",
    },
    featuredProductId: "6",
    image: "/recipes/protein-smoothie.png",
  },
  {
    slug: "protein-baked-oats",
    title: "Protein Baked Oats",
    summary:
      "A cakey, oven-baked single-serving oat bake that eats like a dessert but is built around a full scoop of protein powder.",
    prepTime: "5 min",
    cookTime: "20-25 min",
    servings: "1",
    ingredients: [
      "1/2 cup old-fashioned oats",
      "1 scoop (about 30g) protein powder",
      "1/2 tsp baking powder",
      "1 ripe banana, mashed",
      "1/3 cup milk of choice",
      "1 egg white",
      "Pinch of cinnamon",
    ],
    instructions: [
      "Preheat the oven to 350°F (175°C) and lightly grease a small oven-safe ramekin or baking dish.",
      "In a bowl, mix the oats, protein powder, baking powder, and cinnamon.",
      "Add the mashed banana, milk, and egg white, and stir until fully combined into a thick batter.",
      "Pour into the prepared dish and smooth the top.",
      "Bake for 20-25 minutes, until the top is golden and a toothpick comes out clean.",
      "Let cool for 5 minutes before eating — it firms up as it cools.",
    ],
    tip: "This is a good way to use up a protein powder flavor you're not thrilled about drinking — baking mutes strong or artificial-tasting flavors more than blending does.",
    nutrition: {
      calories: "~340 kcal",
      protein: "~30g",
      carbs: "~40g",
      fat: "~7g",
    },
    featuredProductId: "86",
    image: "/recipes/protein-baked-oats.png",
  },
  {
    slug: "protein-ice-cream",
    title: "Protein Ice Cream (Nice Cream)",
    summary:
      "Frozen banana blended with protein powder into a soft-serve texture — no ice cream maker, no added sugar, and a real dessert once your macros are otherwise spent.",
    prepTime: "5 min (plus freezing the banana ahead)",
    cookTime: "None",
    servings: "1",
    ingredients: [
      "2 ripe bananas, sliced and frozen overnight",
      "1 scoop (about 30g) protein powder, chocolate or vanilla work best",
      "2-3 tbsp milk of choice",
      "Optional mix-ins: peanut butter, cocoa powder, crushed nuts",
    ],
    instructions: [
      "Add the frozen banana slices to a food processor or high-powered blender.",
      "Add the protein powder and 2 tbsp of milk.",
      "Blend, stopping to scrape down the sides, adding another tablespoon of milk if it's too thick to move.",
      "Blend until it reaches a smooth, soft-serve consistency — this can take a couple of minutes with a lot of scraping.",
      "Fold in any mix-ins by hand, then eat immediately or freeze for 30 minutes for a firmer scoop.",
    ],
    tip: "Use very ripe, spotty bananas before freezing them — they blend smoother and taste sweeter than underripe ones, which matters more here since there's no added sugar to cover for it.",
    nutrition: {
      calories: "~290 kcal",
      protein: "~28g",
      carbs: "~35g",
      fat: "~4g",
    },
    featuredProductId: "108",
    image: "/recipes/protein-ice-cream.png",
  },
  {
    slug: "protein-marshmallows",
    title: "Protein Marshmallows",
    summary:
      "Homemade marshmallows with protein powder whipped into the batch — a fun way to turn a sweet-tooth craving into something that also counts toward your daily protein.",
    prepTime: "20 min (plus 4+ hours to set)",
    cookTime: "10 min",
    servings: "About 24 marshmallows",
    ingredients: [
      "3 packets (about 21g) unflavored gelatin",
      "1 cup cold water, divided",
      "1 cup granulated sugar",
      "1/2 cup light corn syrup",
      "1/4 tsp salt",
      "1 scoop (about 30g) vanilla protein powder",
      "1 tsp vanilla extract",
      "1/4 cup powdered sugar or cornstarch, for dusting the pan",
    ],
    instructions: [
      "Line an 8x8-inch pan with parchment paper and dust generously with powdered sugar or cornstarch.",
      "Sprinkle the gelatin over 1/2 cup of cold water in the bowl of a stand mixer and let it bloom for about 10 minutes while you make the syrup.",
      "In a small saucepan, combine the remaining 1/2 cup water, granulated sugar, corn syrup, and salt. Bring to a boil over medium heat and cook until it reaches 240°F (soft-ball stage) on a candy thermometer.",
      "With the mixer on low, slowly pour the hot syrup into the bloomed gelatin. Once it's all incorporated, increase the speed to high and whip for 10-12 minutes, until the mixture is thick, glossy, and roughly triples in volume.",
      "Add the vanilla extract, then sift the protein powder over the top and fold it in gently by hand — whipping it on the mixer at this point can deflate the batch.",
      "Working quickly, spread the mixture into the prepared pan with a greased spatula. Dust the top with more powdered sugar or cornstarch.",
      "Let set uncovered at room temperature for at least 4 hours, or overnight.",
      "Turn out onto a cutting board, cut into squares with a pizza cutter or greased knife, and toss the cut pieces in more powdered sugar or cornstarch so they don't stick together.",
    ],
    tip: "Fold the protein powder in by hand after the whipping is done, not before — running protein powder through a stand mixer at high speed for 10+ minutes tends to knock the air back out and leaves you with dense, gummy marshmallows instead of light ones.",
    nutrition: {
      calories: "~45 kcal per marshmallow",
      protein: "~3g per marshmallow",
      carbs: "~7g per marshmallow",
      fat: "~0g per marshmallow",
    },
    featuredProductId: "7",
    image: "/recipes/protein-marshmallows.png",
  },
  {
    slug: "bariatric-protein-pudding",
    title: "Bariatric-Friendly Protein Pudding",
    summary:
      "A silky, sugar-free protein pudding built for small portions and the pureed stage — thick enough to feel like a treat, gentle enough to sit well.",
    prepTime: "5 min",
    cookTime: "None (chill 1 hour)",
    servings: "2 small portions (about 1/2 cup each)",
    ingredients: [
      "1 scoop (about 30g) vanilla protein powder",
      "1 box (1 oz) sugar-free instant pudding mix, vanilla or chocolate",
      "1 1/2 cups unsweetened almond milk or skim milk",
      "1/4 tsp vanilla extract (optional)",
    ],
    instructions: [
      "In a bowl, whisk the sugar-free pudding mix with the milk for about 2 minutes, until it starts to thicken.",
      "Add the protein powder and vanilla extract, and whisk again until completely smooth with no clumps.",
      "Divide into small portions (about 1/2 cup each) — this is meant to be eaten slowly in small amounts, not all at once.",
      "Refrigerate for at least 1 hour before eating, until fully set.",
    ],
    tip: "Whisk the pudding mix into the milk before adding the protein powder — mixing protein powder into an already-thick pudding base is what causes the lumps.",
    nutrition: {
      calories: "~90 kcal per portion",
      protein: "~15g per portion",
      carbs: "~5g per portion",
      fat: "~1g per portion",
    },
    featuredProductId: "8",
    image: "/recipes/bariatric-protein-pudding.png",
    bariatricApproved: true,
  },
  {
    slug: "bariatric-protein-hot-cocoa",
    title: "Bariatric-Friendly Protein Hot Cocoa",
    summary:
      "A warm, sippable chocolate protein drink — small portion, no added sugar, and easy to get down slowly on days when food doesn't sound appealing.",
    prepTime: "5 min",
    cookTime: "3 min",
    servings: "1 small portion (about 3/4 cup)",
    ingredients: [
      "3/4 cup unsweetened almond milk or skim milk",
      "1 scoop (about 30g) chocolate protein powder",
      "1 tsp unsweetened cocoa powder",
      "Sugar-free sweetener to taste (optional)",
    ],
    instructions: [
      "Warm the milk in a small saucepan over low heat, or in the microwave for 60-90 seconds — it should be warm, not boiling.",
      "Whisk in the cocoa powder until dissolved.",
      "Let the milk cool slightly, then whisk in the protein powder until smooth.",
      "Sip slowly rather than drinking quickly — this is a small-portion drink meant to be taken over time, not gulped.",
    ],
    tip: "Let the milk cool for a minute or two off the heat before adding protein powder — whisking it into near-boiling liquid is the most common cause of a grainy, clumped hot cocoa.",
    nutrition: {
      calories: "~130 kcal",
      protein: "~25g",
      carbs: "~6g",
      fat: "~2g",
    },
    featuredProductId: "33",
    image: "/recipes/bariatric-protein-hot-cocoa.png",
    bariatricApproved: true,
  },
  {
    slug: "bariatric-protein-broth-soup",
    title: "Bariatric-Friendly Protein Broth Soup",
    summary:
      "A warm, savory blended soup with unflavored protein stirred in — built for the soft-food and pureed stages when a shake feels like too much but broth alone isn't enough.",
    prepTime: "5 min",
    cookTime: "10 min",
    servings: "2 small portions (about 1 cup each)",
    ingredients: [
      "2 cups low-sodium chicken or vegetable broth",
      "1 scoop (about 20-30g) unflavored collagen or protein powder",
      "1/4 cup well-cooked, soft-pureed vegetables (carrot, squash, or potato), optional",
      "Pinch of salt and pepper to taste",
    ],
    instructions: [
      "Warm the broth in a saucepan over medium-low heat until hot but not boiling.",
      "If using pureed vegetables, stir them in and let the soup return to a gentle simmer.",
      "Remove from heat and let cool slightly for a minute or two.",
      "Whisk in the unflavored protein powder until fully dissolved, with no floating clumps.",
      "Season lightly and serve warm, sipping or spooning slowly in small amounts.",
    ],
    tip: "Unflavored collagen peptides dissolve into hot liquid without clouding it or adding a whey taste, which is why they work better than a flavored whey powder in a savory soup like this one.",
    nutrition: {
      calories: "~70 kcal per portion",
      protein: "~14g per portion",
      carbs: "~2g per portion",
      fat: "~0g per portion",
    },
    featuredProductId: "109",
    image: "/recipes/bariatric-protein-broth-soup.png",
    bariatricApproved: true,
  },
  {
    slug: "bariatric-protein-popsicles",
    title: "Bariatric-Friendly Protein Popsicles",
    summary:
      "Slow-melting, low-sugar protein popsicles — a way to get fluids and protein in without a straw or a full glass to finish.",
    prepTime: "5 min (plus 4+ hours to freeze)",
    cookTime: "None",
    servings: "6 small popsicles",
    ingredients: [
      "2 scoops (about 40-50g) protein powder, any flavor",
      "2 cups unsweetened almond milk or water",
      "Sugar-free sweetener to taste (optional)",
    ],
    instructions: [
      "In a bowl or blender, whisk or blend the protein powder into the milk until completely smooth.",
      "Taste and add a sugar-free sweetener if you'd like it sweeter.",
      "Pour into a popsicle mold, filling each cavity about 3/4 full to leave room for expansion.",
      "Freeze for at least 4 hours, or until completely solid.",
      "Run the mold briefly under warm water to release the popsicles before eating.",
    ],
    tip: "Fill the molds only 3/4 full — protein-based mixes expand slightly more than plain juice popsicles when they freeze, and overfilled molds tend to overflow or crack.",
    nutrition: {
      calories: "~45 kcal per popsicle",
      protein: "~8g per popsicle",
      carbs: "~2g per popsicle",
      fat: "~0g per popsicle",
    },
    featuredProductId: "118",
    image: "/recipes/bariatric-protein-popsicles.png",
    bariatricApproved: true,
  },
  {
    slug: "bariatric-protein-egg-bites",
    title: "Bariatric-Friendly Protein Egg Bites",
    summary:
      "Soft, mini baked egg bites with unflavored protein mixed into the batter — an easy make-ahead option for the soft-food stage that isn't sweet.",
    prepTime: "10 min",
    cookTime: "20 min",
    servings: "12 mini bites",
    ingredients: [
      "6 eggs",
      "1/4 cup cottage cheese or plain Greek yogurt",
      "1 scoop (about 20g) unflavored collagen or protein powder",
      "1/4 cup finely diced soft-cooked vegetables (spinach, bell pepper), optional",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat the oven to 325°F (165°C) and grease a 12-cup mini muffin tin well.",
      "In a blender, combine the eggs, cottage cheese or yogurt, and protein powder. Blend until completely smooth.",
      "Stir in any diced vegetables by hand, then season with salt and pepper.",
      "Divide the mixture evenly among the muffin cups, filling each about 3/4 full.",
      "Bake for 18-20 minutes, until the centers are set and no longer jiggle.",
      "Let cool for 5 minutes before removing from the tin — they'll firm up further as they cool.",
    ],
    tip: "Blending the eggs and protein powder together, instead of just whisking, gives these a smoother, less rubbery texture — which matters more here than in a regular omelet since these are meant to be easy to chew and swallow.",
    nutrition: {
      calories: "~40 kcal per bite",
      protein: "~5g per bite",
      carbs: "~1g per bite",
      fat: "~2g per bite",
    },
    featuredProductId: "62",
    image: "/recipes/bariatric-protein-egg-bites.png",
    bariatricApproved: true,
  },
  {
    slug: "bariatric-protein-gelatin-cups",
    title: "Bariatric-Friendly Protein Gelatin Cups",
    summary:
      "Jiggly, sugar-free protein gelatin cups — an easy, portion-controlled way to work in protein between meals without anything to chew.",
    prepTime: "10 min (plus 2+ hours to set)",
    cookTime: "5 min",
    servings: "4 small cups",
    ingredients: [
      "2 packets (about 14g) unflavored gelatin",
      "2 cups water, divided",
      "1 scoop (about 30g) flavored protein powder",
      "Sugar-free sweetener to taste (optional)",
    ],
    instructions: [
      "Sprinkle the gelatin over 1/2 cup of cold water in a bowl and let it bloom for 5-10 minutes.",
      "Heat the remaining 1 1/2 cups of water until hot but not boiling, then whisk it into the bloomed gelatin until fully dissolved.",
      "Let the mixture cool for a few minutes, then whisk in the protein powder until smooth.",
      "Pour into 4 small cups or ramekins.",
      "Refrigerate for at least 2 hours, until fully set and jiggly.",
    ],
    tip: "Whisking the protein powder in after the gelatin liquid has cooled slightly, rather than while it's still hot, keeps the texture smooth instead of grainy or clumped.",
    nutrition: {
      calories: "~60 kcal per cup",
      protein: "~13g per cup",
      carbs: "~2g per cup",
      fat: "~0g per cup",
    },
    featuredProductId: "32",
    image: "/recipes/bariatric-protein-gelatin-cups.png",
    bariatricApproved: true,
  },
  {
    slug: "protein-waffles",
    title: "Protein Waffles",
    summary:
      "Crisp on the outside, fluffy inside — a waffle iron turns the same protein pancake batter into something that holds up better to toppings.",
    prepTime: "5 min",
    cookTime: "15 min",
    servings: "2 (about 4 waffles)",
    ingredients: [
      "1 scoop (about 30g) vanilla protein powder",
      "1 cup old-fashioned oats, blended into flour",
      "1 tsp baking powder",
      "2 eggs",
      "3/4 cup milk of choice",
      "1 tbsp melted butter or oil",
      "1/2 tsp vanilla extract",
    ],
    instructions: [
      "Preheat your waffle iron and lightly grease it.",
      "Blend the oats into a fine flour, then whisk together with the protein powder and baking powder in a bowl.",
      "In a separate bowl, whisk the eggs, milk, melted butter, and vanilla together.",
      "Combine the wet and dry ingredients and stir until just mixed.",
      "Pour batter onto the hot waffle iron and cook according to your iron's instructions, usually 3-5 minutes, until golden and crisp.",
      "Repeat with the remaining batter. Serve with fruit or a light drizzle of syrup.",
    ],
    tip: "Protein-powder batters cook a little faster than regular waffle batter because there's less starch to set — check yours a minute or two before your iron's usual waffle time to avoid overcooking.",
    nutrition: {
      calories: "~340 kcal",
      protein: "~26g",
      carbs: "~34g",
      fat: "~10g",
    },
    featuredProductId: "18",
    image: "/recipes/protein-waffles.png",
  },
  {
    slug: "protein-french-toast",
    title: "Protein French Toast",
    summary:
      "A ready-to-drink protein milk swapped in for regular milk turns a basic French toast soak into a genuine protein source, not just a carb delivery vehicle.",
    prepTime: "5 min",
    cookTime: "10 min",
    servings: "2 (4 slices)",
    ingredients: [
      "1 can (11 fl oz) vanilla protein milk",
      "2 eggs",
      "1/2 tsp cinnamon",
      "1/2 tsp vanilla extract",
      "4 slices whole-grain bread",
    ],
    instructions: [
      "In a shallow dish, whisk together the protein milk, eggs, cinnamon, and vanilla extract.",
      "Heat a lightly greased non-stick pan or griddle over medium heat.",
      "Dip each bread slice in the mixture for a few seconds per side, letting it soak in without falling apart.",
      "Cook each slice for 2-3 minutes per side, until golden brown and cooked through.",
      "Serve with fruit or a light drizzle of syrup.",
    ],
    tip: "Don't let the bread sit in the soak too long — a few seconds per side is enough. Oversoaking makes it fall apart in the pan instead of holding together.",
    nutrition: {
      calories: "~360 kcal",
      protein: "~30g",
      carbs: "~36g",
      fat: "~10g",
    },
    featuredProductId: "134",
    image: "/recipes/protein-french-toast.png",
  },
  {
    slug: "protein-chia-pudding",
    title: "Protein Chia Pudding",
    summary:
      "Chia seeds thicken this into a pudding-like texture overnight, and a scoop of strawberry protein turns it into a full breakfast instead of a snack.",
    prepTime: "5 min (plus overnight in the fridge)",
    cookTime: "None",
    servings: "1",
    ingredients: [
      "3 tbsp chia seeds",
      "1 scoop (about 30g) strawberry protein powder",
      "1 cup milk of choice",
      "1/2 tsp vanilla extract",
      "Toppings: sliced strawberries or granola",
    ],
    instructions: [
      "Whisk the protein powder into the milk first, until fully dissolved.",
      "Add the chia seeds and vanilla extract, and stir well.",
      "Let it sit for 5 minutes, then stir again to break up any chia clumps that formed on the bottom.",
      "Cover and refrigerate for at least 4 hours, ideally overnight, until thickened to a pudding consistency.",
      "Top with fruit or granola before serving.",
    ],
    tip: "Stir twice — once right after mixing, and again after the first 5 minutes. Chia seeds clump if left undisturbed early on, and one stir alone isn't enough to break that up.",
    nutrition: {
      calories: "~310 kcal",
      protein: "~30g",
      carbs: "~24g",
      fat: "~11g",
    },
    featuredProductId: "15",
    image: "/recipes/protein-chia-pudding.png",
  },
  {
    slug: "protein-energy-balls",
    title: "Protein Energy Balls",
    summary:
      "No-bake bites made by crushing a protein bar into the mix — an easy way to stretch a box of bars into more servings, or use up a flavor you're bored of.",
    prepTime: "15 min",
    cookTime: "None",
    servings: "12 balls",
    ingredients: [
      "2 protein bars, chopped or crumbled",
      "1 cup old-fashioned oats",
      "1/3 cup peanut butter or almond butter",
      "2-3 tbsp honey or maple syrup",
      "2 tbsp mini chocolate chips (optional)",
    ],
    instructions: [
      "In a food processor, pulse the crumbled protein bars and oats together until coarsely ground.",
      "Add the peanut butter and honey, and pulse again until the mixture holds together when pressed.",
      "Transfer to a bowl and fold in chocolate chips by hand if using.",
      "Roll into 12 balls, about 1 tablespoon each.",
      "Refrigerate for at least 30 minutes to firm up before eating.",
    ],
    tip: "If the mixture is too dry to hold together, add honey a teaspoon at a time rather than all at once — protein bars vary in moisture, so the amount you need changes depending on which bar you use.",
    nutrition: {
      calories: "~110 kcal per ball",
      protein: "~6g per ball",
      carbs: "~10g per ball",
      fat: "~5g per ball",
    },
    featuredProductId: "143",
    image: "/recipes/protein-energy-balls.png",
  },
  {
    slug: "protein-banana-bread",
    title: "Protein Banana Bread",
    summary:
      "A full loaf of banana bread with unflavored protein blended into the batter, so it tastes like regular banana bread but pulls its weight nutritionally.",
    prepTime: "10 min",
    cookTime: "50 min",
    servings: "1 loaf (about 10 slices)",
    ingredients: [
      "3 ripe bananas, mashed",
      "2 eggs",
      "1/3 cup melted coconut oil or butter",
      "1/3 cup honey or maple syrup",
      "1 1/2 cups flour or oat flour",
      "2 scoops (about 40g) unflavored protein powder",
      "1 tsp baking soda",
      "1/2 tsp cinnamon",
      "Pinch of salt",
    ],
    instructions: [
      "Preheat the oven to 350°F (175°C) and grease a standard loaf pan.",
      "In a large bowl, whisk together the mashed bananas, eggs, melted oil, and honey.",
      "In a separate bowl, whisk the flour, protein powder, baking soda, cinnamon, and salt together to break up any clumps.",
      "Fold the dry ingredients into the wet ingredients until just combined — don't overmix.",
      "Pour into the prepared loaf pan and bake for 45-55 minutes, until a toothpick comes out clean.",
      "Let cool in the pan for 10 minutes, then turn out onto a rack to cool completely before slicing.",
    ],
    tip: "Whisk the protein powder into the dry ingredients first, not directly into the wet batter — that's what stops it from clumping into little dense pockets throughout the loaf.",
    nutrition: {
      calories: "~210 kcal per slice",
      protein: "~12g per slice",
      carbs: "~26g per slice",
      fat: "~7g per slice",
    },
    featuredProductId: "111",
    image: "/recipes/protein-banana-bread.png",
  },
  {
    slug: "protein-yogurt-bark",
    title: "Protein Yogurt Bark",
    summary:
      "Frozen yogurt bark studded with fruit and a scoop of protein blended in — snap off a piece as a quick high-protein snack straight from the freezer.",
    prepTime: "10 min (plus 3+ hours to freeze)",
    cookTime: "None",
    servings: "About 8 pieces",
    ingredients: [
      "2 cups plain Greek yogurt",
      "1 scoop (about 30g) unflavored or vanilla protein powder",
      "2 tbsp honey",
      "1/2 cup mixed berries, sliced",
      "2 tbsp granola or crushed nuts",
    ],
    instructions: [
      "Line a baking sheet with parchment paper.",
      "In a bowl, whisk the Greek yogurt, protein powder, and honey together until completely smooth.",
      "Spread the mixture evenly onto the parchment paper, about 1/4 inch thick.",
      "Scatter the berries and granola over the top, pressing gently so they stick.",
      "Freeze for at least 3 hours, until solid.",
      "Break into pieces and store in the freezer in an airtight container or bag.",
    ],
    tip: "Spread it evenly to about 1/4 inch thick — thicker spots take much longer to freeze solid and stay chewy instead of snapping cleanly like bark.",
    nutrition: {
      calories: "~90 kcal per piece",
      protein: "~10g per piece",
      carbs: "~8g per piece",
      fat: "~2g per piece",
    },
    featuredProductId: "63",
    image: "/recipes/protein-yogurt-bark.png",
  },
  {
    slug: "protein-cookie-dough-bites",
    title: "Protein Cookie Dough Bites",
    summary:
      "Edible, egg-free cookie dough bites built around chocolate peanut butter protein powder — tastes like the bowl you'd sneak from before baking, minus the raw egg and flour.",
    prepTime: "10 min",
    cookTime: "None",
    servings: "14 bites",
    ingredients: [
      "1 cup oat flour (or old-fashioned oats blended into flour)",
      "1 scoop (about 30g) chocolate peanut butter protein powder",
      "1/4 cup peanut butter",
      "2-3 tbsp milk of choice",
      "2 tbsp mini chocolate chips",
    ],
    instructions: [
      "In a bowl, whisk the oat flour and protein powder together to break up any clumps.",
      "Add the peanut butter and 2 tablespoons of milk, and mix until a thick dough forms, adding more milk a teaspoon at a time if it's too dry.",
      "Fold in the chocolate chips.",
      "Roll into 14 small balls, about 1 tablespoon each.",
      "Refrigerate for at least 20 minutes to firm up before eating.",
    ],
    tip: "Oat flour is safe to eat raw where regular wheat flour isn't — heat-treated oats carry much lower risk, which is what makes this dough actually edible without baking it.",
    nutrition: {
      calories: "~90 kcal per bite",
      protein: "~6g per bite",
      carbs: "~7g per bite",
      fat: "~4g per bite",
    },
    featuredProductId: "19",
    image: "/recipes/protein-cookie-dough-bites.png",
  },
  {
    slug: "protein-hot-chocolate",
    title: "Protein Hot Chocolate",
    summary:
      "A thick, rich hot chocolate made with casein protein instead of whey — casein's naturally creamy texture makes this taste closer to melted chocolate than a thin cocoa packet.",
    prepTime: "2 min",
    cookTime: "5 min",
    servings: "1",
    ingredients: [
      "1 cup milk of choice",
      "1 scoop (about 30g) chocolate casein protein powder",
      "1 tsp unsweetened cocoa powder",
      "Mini marshmallows or whipped cream, for topping (optional)",
    ],
    instructions: [
      "Warm the milk in a small saucepan over medium-low heat, or in the microwave for about 90 seconds.",
      "Whisk in the cocoa powder until fully dissolved.",
      "Remove from heat and let cool for a minute, then whisk in the protein powder until smooth and no clumps remain.",
      "Pour into a mug and top with marshmallows or whipped cream if using.",
    ],
    tip: "Casein is thicker and slower to dissolve than whey, so whisk longer and more vigorously than you would for a whey-based drink — it's worth the extra effort for how creamy the final texture comes out.",
    nutrition: {
      calories: "~220 kcal",
      protein: "~28g",
      carbs: "~10g",
      fat: "~5g",
    },
    featuredProductId: "84",
    image: "/recipes/protein-hot-chocolate.png",
  },
  {
    slug: "protein-cheesecake-cups",
    title: "Protein Cheesecake Cups",
    summary:
      "No-bake, single-serving cheesecake cups with a crushed cookie base and a protein-boosted filling — all the richness of cheesecake, portioned out so you're not committed to a whole slice.",
    prepTime: "15 min (plus 2+ hours to chill)",
    cookTime: "None",
    servings: "4 cups",
    ingredients: [
      "8 sandwich cookies, crushed",
      "2 tbsp melted butter",
      "8 oz cream cheese, softened",
      "1 scoop (about 30g) cookies and cream protein powder",
      "1/4 cup Greek yogurt",
      "2 tbsp honey or sugar-free sweetener",
    ],
    instructions: [
      "Mix the crushed cookies with the melted butter, then press into the bottom of 4 small cups or jars to form a crust.",
      "In a bowl, beat the softened cream cheese until smooth.",
      "Add the protein powder, Greek yogurt, and honey, and beat again until fully combined and creamy.",
      "Spoon or pipe the filling over the crusts in each cup.",
      "Refrigerate for at least 2 hours before eating, until set and chilled through.",
    ],
    tip: "Make sure the cream cheese is fully softened to room temperature before mixing — cold cream cheese is what causes lumpy filling no matter how long you beat it.",
    nutrition: {
      calories: "~310 kcal per cup",
      protein: "~18g per cup",
      carbs: "~20g per cup",
      fat: "~17g per cup",
    },
    featuredProductId: "13",
    image: "/recipes/protein-cheesecake-cups.png",
  },
  {
    slug: "protein-fruit-popsicles",
    title: "Protein Fruit Popsicles",
    summary:
      "Real fruit blended with a scoop of protein and frozen into popsicles — a lighter, fruitier alternative to the chocolate and vanilla recipes in this list.",
    prepTime: "10 min (plus 4+ hours to freeze)",
    cookTime: "None",
    servings: "6 popsicles",
    ingredients: [
      "1 scoop (about 30g) orange or citrus-flavored protein powder",
      "1 cup orange juice",
      "1 cup Greek yogurt",
      "1/2 cup fresh or frozen mango or peach chunks",
    ],
    instructions: [
      "Add the orange juice and protein powder to a blender and blend until fully dissolved.",
      "Add the Greek yogurt and fruit, and blend again until smooth.",
      "Pour into a popsicle mold, filling each cavity about 3/4 full.",
      "Insert popsicle sticks and freeze for at least 4 hours, until completely solid.",
      "Run the mold briefly under warm water to release the popsicles before eating.",
    ],
    tip: "Blend the protein powder into the juice before adding the yogurt and fruit — mixing it into the thinnest liquid first is what keeps it from clumping once the mixture gets thicker.",
    nutrition: {
      calories: "~70 kcal per popsicle",
      protein: "~7g per popsicle",
      carbs: "~9g per popsicle",
      fat: "~1g per popsicle",
    },
    featuredProductId: "9",
    image: "/recipes/protein-fruit-popsicles.png",
  },
  {
    slug: "protein-blondies",
    title: "Protein Blondies",
    summary:
      "Chewy, chocolate-chip-studded blondies with a scoop of protein baked into the batter — dessert that doesn't derail the rest of your day's macros.",
    prepTime: "10 min",
    cookTime: "25 min",
    servings: "9 squares",
    ingredients: [
      "1 cup almond flour or oat flour",
      "1 scoop (about 30g) chocolate protein powder",
      "1/2 tsp baking soda",
      "Pinch of salt",
      "1/3 cup melted butter or coconut oil",
      "1/3 cup brown sugar or coconut sugar",
      "1 egg",
      "1 tsp vanilla extract",
      "1/3 cup chocolate chips",
    ],
    instructions: [
      "Preheat the oven to 350°F (175°C) and line an 8x8-inch baking pan with parchment paper.",
      "Whisk the flour, protein powder, baking soda, and salt together in a bowl.",
      "In a separate bowl, whisk the melted butter, brown sugar, egg, and vanilla until smooth.",
      "Combine the wet and dry ingredients, stirring until just mixed, then fold in the chocolate chips.",
      "Spread into the prepared pan and bake for 22-25 minutes, until the edges are golden and the center is just set.",
      "Let cool completely in the pan before cutting into 9 squares.",
    ],
    tip: "Pull these from the oven when the center still looks slightly underdone — they firm up a lot as they cool, and baking until they look fully done in the oven usually means dry blondies once cooled.",
    nutrition: {
      calories: "~180 kcal per square",
      protein: "~9g per square",
      carbs: "~15g per square",
      fat: "~11g per square",
    },
    featuredProductId: "11",
    image: "/recipes/protein-blondies.png",
  },
  {
    slug: "protein-donuts",
    title: "Baked Protein Donuts",
    summary:
      "Baked, not fried, in a donut pan — a scoop of cookies-and-cream protein gives these a malty sweetness without needing much added sugar.",
    prepTime: "10 min",
    cookTime: "12 min",
    servings: "6 donuts",
    ingredients: [
      "1 cup oat flour",
      "1 scoop (about 30g) cookies and cream protein powder",
      "1 tsp baking powder",
      "2 eggs",
      "1/3 cup milk of choice",
      "2 tbsp honey or maple syrup",
      "1 tbsp melted butter or oil",
    ],
    instructions: [
      "Preheat the oven to 350°F (175°C) and grease a 6-cavity donut pan.",
      "Whisk the oat flour, protein powder, and baking powder together in a bowl.",
      "In a separate bowl, whisk the eggs, milk, honey, and melted butter together.",
      "Combine wet and dry ingredients and stir until just mixed.",
      "Spoon or pipe the batter into the donut pan cavities, filling each about 2/3 full.",
      "Bake for 10-12 minutes, until a toothpick comes out clean.",
      "Let cool in the pan for 5 minutes before turning out onto a rack.",
    ],
    tip: "Fill the cavities only 2/3 full — donut batter rises to fill the ring shape, and overfilled cavities bake into a solid disc instead of a donut with a hole.",
    nutrition: {
      calories: "~150 kcal per donut",
      protein: "~11g per donut",
      carbs: "~16g per donut",
      fat: "~5g per donut",
    },
    featuredProductId: "85",
    image: "/recipes/protein-donuts.png",
  },
  {
    slug: "electrolyte-popsicles",
    title: "Electrolyte Popsicles",
    summary:
      "An electrolyte drink mix frozen into popsicles — slower to get down than a full glass, which makes them a good option after a hot workout when chugging fluids doesn't sound appealing.",
    prepTime: "5 min (plus 4+ hours to freeze)",
    cookTime: "None",
    servings: "6 popsicles",
    ingredients: [
      "2 packets electrolyte drink mix, any flavor",
      "3 cups water",
      "1/2 cup fresh fruit, diced (optional, for texture and flavor)",
    ],
    instructions: [
      "Stir the electrolyte drink mix into the water until fully dissolved.",
      "If using, divide the diced fruit evenly among the popsicle mold cavities.",
      "Pour the electrolyte mixture into the mold, filling each cavity about 3/4 full.",
      "Insert popsicle sticks and freeze for at least 4 hours, until completely solid.",
      "Run the mold briefly under warm water to release the popsicles before eating.",
    ],
    tip: "Adding a bit of diced fruit to the mold before pouring in the liquid keeps it suspended throughout the popsicle instead of all sinking to the bottom.",
    nutrition: {
      calories: "~15 kcal per popsicle",
      protein: "~0g per popsicle",
      carbs: "~4g per popsicle",
      fat: "~0g per popsicle",
    },
    featuredProductId: "45",
    image: "/recipes/electrolyte-popsicles.png",
  },
  {
    slug: "electrolyte-infused-water",
    title: "Electrolyte Infused Water",
    summary:
      "A pitcher of lightly flavored, electrolyte-boosted water built for sipping throughout the day — an easy habit for anyone who struggles to drink enough plain water.",
    prepTime: "5 min",
    cookTime: "None",
    servings: "8 cups (1 pitcher)",
    ingredients: [
      "1 packet electrolyte drink mix",
      "8 cups cold water",
      "1 lemon or orange, sliced",
      "A few sprigs of mint (optional)",
    ],
    instructions: [
      "Fill a large pitcher with the cold water.",
      "Stir in the electrolyte drink mix until fully dissolved.",
      "Add the sliced citrus and mint, pressing gently to release some of the natural oils and juice.",
      "Refrigerate for at least 30 minutes before serving so the flavors have time to infuse.",
      "Stir before pouring, since some flavor settles at the bottom.",
    ],
    tip: "Slice the citrus rather than juicing it — whole slices infuse more slowly and evenly over the course of the day instead of dumping all their flavor in at once.",
    nutrition: {
      calories: "~10 kcal per cup",
      protein: "~0g per cup",
      carbs: "~2g per cup",
      fat: "~0g per cup",
    },
    featuredProductId: "94",
    image: "/recipes/electrolyte-infused-water.png",
  },
];

export function getRecipeBySlug(slug: string): Recipe | undefined {
  return RECIPES.find((r) => r.slug === slug);
}
